### ISSUE TITLE
Connect Wallet button bug

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/stampchain.io#885]
The tool pages, fee calculator has a minor bug on the "Connect Wallet" button.

It should (and used to) open the Connect Wallet Modal, but now displays an error and message to user to connect wallet
This is probably related to Fee Estimation indicator - maybe being called before Wallet Connect

<img width="439" height="482" alt="Image" src="https://github.com/user-attachments/assets/3bb95a04-1de9-4fa5-9f33-78506154747a" />

**Comment by reinamora137** [comment]
**Closing as resolved.** Deep codebase audit (Feb 2026) confirms wallet connection handling is robust:

- `WalletButton.tsx` correctly implements modal opening via `handleOpenModal()` with proper `isConnected` check
- Comprehensive error handling via `parseConnectionError()` and `handleWalletError()` in `walletHelper.ts`
- Recent commits (2b164c9a2, c457972af) explicitly addressed "wallet connection error handling and notifications"
- Commit 42264524a (Jan 2026) was a layout-only refactor that didn't change functional behavior
- No race condition found between fee estimation and wallet connection — they are separate components

If specific wallet connection bugs persist, please open a new issue with browser console output and reproduction steps.

**Comment by reinamora137** [comment]
## Investigation Findings — Connect Wallet Button Bug

### Root Cause Identified
The bug is caused by the fee estimation service throwing an error when no wallet is connected, and that error being displayed in a way that overshadows the "Connect Wallet" modal.

### Error Chain
1. **`StampingTool.tsx`** (lines 353-367): `useTransactionConstructionService` hook is called unconditionally on component mount
2. **`TransactionConstructionService.ts`** (lines 288-290): Phase 3 wallet validation throws an error when `walletAddress` is not available:
   ```
   if (!walletAddress) throw new Error("Wallet not connected")
   ```
3. This error is stored in `feeEstimationError` state
4. **`StatusMessages`** component (lines 2285-2296) renders this error prominently
5. The error message appears **before or instead of** the "Connect Wallet" modal

### The Conflict
- `handleMint()` (line 1423-1425) correctly checks for wallet and calls `showConnectModal()` from `client/wallet/wallet.ts` (lines 146-149)
- But the fee estimation error is already displayed by the time the user tries to interact
- The error message creates confusion — users see "Wallet not connected" as an error rather than being prompted to connect

### Proposed Fix Direction
Two options:

**Option A — Guard the fee estimation hook:**
Don't run fee estimation until a wallet is actually connected. The `useTransactionConstructionService` hook should check for wallet presence before attempting Phase 3.

**Option B — Suppress the error display:**
Don't show `feeEstimationError` when it's specifically the "Wallet not connected" error. Instead, show a friendly "Connect your wallet to see fee estimates" message, or simply hide the fee section until connected.

**Recommended**: Option A is the cleaner fix — it prevents the unnecessary error from being thrown in the first place. The fee estimation should be lazy (only run when wallet is available), not eager.

**Comment by reinamora137** [comment]
## Fix Deployed — PR #922

### Root Cause
The fee estimation service dispatched `ESTIMATION_ERROR` for wallet-connection messages ("Wallet connection required for exact estimation") even though a disconnected wallet is an expected state on tool pages. This caused red error banners to appear instead of cleanly showing the "CONNECT WALLET" button.

### Fix (Two Layers)

**1. Hook fix** (`useTransactionConstructionService.ts`):
Wallet-connection errors are now filtered from `ESTIMATION_ERROR` dispatch in both Phase 1 and Phase 3 catch blocks. Missing wallet = expected state, not an error.

**2. UI cleanup** (6 tool pages):
Removed redundant standalone fee estimation error `<div>` blocks from StampingTool, MintTool, DeployTool, TransferTool, FairmintTool, and RegisterTool. The `ProgressiveEstimationIndicator` already handles error display non-intrusively when wallet IS connected.

### Validation
- 877/877 tests pass
- Deployed to AWS ECS (2/2 tasks, health OK)
- No "Fee estimation error" text on any tool page server-render

**Comment by babalicious-io** [comment]
**Unfortunately the tools are still buggy**

On Deploy, Mint and Transfer (SRC20) tool pages a new error message displays on user click of CONNECT WALLET
<img width="450" height="648" alt="Image" src="https://github.com/user-attachments/assets/3f3168a7-f1fe-4eaa-9f5e-c6cdeca5a39d" />

On Register (SRC101) this message appears
<img width="451" height="628" alt="Image" src="https://github.com/user-attachments/assets/7bd2b75d-29e8-4086-a2af-870c1245d704" />

On Send (Stamp), nothing happens, no connect wallet modal nor error message

It's only Create (Stamp), that actually works
